version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test

  upload-to-codecov:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Upload to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN

workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - upload-to-codecov:
          requires:
            - build-and-test

orbs:
  codecov: codecov/codecov@volatile
  maven: circleci/maven@1.1.0
