version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - upload-to-codecov:
          requires:
            - build-and-test

orbs:
  codecov: codecov/codecov@1.1.0
  maven: circleci/maven@1.1.0
